"""Export measured results to `docs/data.js` for the article page's widgets.

**Why the widgets read exported artefacts rather than recomputing.** This
project spent an audit (F135-F141) finding places where a number in prose had
drifted from the artefact it came from. A widget that recomputes physics in
JavaScript is a fourth implementation and a fifth chance to drift. Everything
here that is a *result* is therefore read from the experiment's own
`results.json` / `traces.npz` and shipped verbatim; only the tire curve is
recomputed live in `docs/tire.js`, and that carries a known-answer check
against Python.

    python -m tools.export_web_data
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

import physics.track as T

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "data.js"
#: Where the scrubber's resolution goes. Sampling uniformly in distance spends
#: two thirds of the slider on the exit straight, where nothing changes, and
#: leaves only eight steps for the corner itself -- exactly backwards. So: keep
#: every solver node out to FOCUS_M (braking, turn-in, the corner, and the
#: stretch of exit where the two drivetrains actually separate), then thin the
#: long tail where the trace is flat.
FOCUS_M = 220.0
TAIL_STEP = 4
FRACS = (0.40, 0.47, 0.54, 0.61, 0.65)
#: Front-mass fraction and polar moment per archetype, from Episode 8's table.
#: They are inputs to that experiment rather than outputs, so they are not in
#: results.json and are restated here.
LAYOUT_INPUTS = {
    "front_fwd": (0.62, 1.25), "front_rwd": (0.55, 1.20),
    "front_mid_rwd": (0.53, 1.00), "mid_rwd": (0.43, 0.80),
    "rear_rwd": (0.38, 1.22),
}


def _r(a, n=3):
    return [round(float(v), n) for v in a]


def main() -> int:
    z6 = np.load(ROOT / "experiments/ep06/out/traces.npz")
    r6 = json.loads((ROOT / "experiments/ep06/out/results.json").read_text())
    r7 = json.loads((ROOT / "experiments/ep07/out/results.json").read_text())
    r8 = json.loads((ROOT / "experiments/ep08/out/results.json").read_text())
    r15 = json.loads((ROOT / "experiments/ep15/out/results.json").read_text())
    trk = T.long_exit()

    wheels = {}
    for drv in ("rwd", "fwd"):
        s = z6[f"{drv}_s"] if f"{drv}_s" in z6.files else np.linspace(0, trk.length, 100)
        keep = [i for i in range(len(s))
                if s[i] <= FOCUS_M or i % TAIL_STEP == 0]
        d = {"s": _r(s[keep], 1), "n": _r(z6[f"{drv}_n"][keep], 3)}
        for c in ("fl", "fr", "rl", "rr"):
            d[c] = {
                "load": _r(z6[f"{drv}_load_{c}"][keep], 0),
                "fx": _r(z6[f"{drv}_fx_{c}"][keep], 0),
                "fy": _r(z6[f"{drv}_fy_{c}"][keep], 0),
                "alpha": _r(z6[f"{drv}_alpha_{c}"][keep], 3),
            }
        wheels[drv] = d

    layout = {}
    for k, v in r8["archetypes"].items():
        front, izz = LAYOUT_INPUTS[k]
        layout[k] = {"front": front, "izz": izz, "rise": v["rise_time"],
                     "K": v["understeer_gradient_deg_per_g"], "lap": v["time_s"]}

    out = {
        "corner": {"length": round(float(trk.length), 1),
                   "entry": round(float(T.ENTRY_STRAIGHT), 1),
                   "arc": round(float(T.CORNER_ARC), 1),
                   "radius": 40.0, "halfWidth": 4.0,
                   "focus": FOCUS_M},
        "wheels": wheels,
        "drivetrain": {
            "lapRwd": r6["rwd_ideal"]["time_s"], "lapFwd": r6["fwd_ideal"]["time_s"],
            "power": [{"kN": float(k), "hp": hp,
                       "rwd": r6["power_sweep"][k]["rwd"]["time_s"],
                       "fwd": r6["power_sweep"][k]["fwd"]["time_s"]}
                      for k, hp in [("2.5", 101), ("4.5", 181), ("7", 282), ("10", 402)]],
        },
        "balance": {
            "frac": list(FRACS),
            "K": [r7["K_deg_per_g"][f"{f:.2f}"] for f in FRACS],
            "rwd": [r7["rows"][f"rwd_{f:.2f}"]["time_s"] for f in FRACS],
            "fwd": [r7["rows"][f"fwd_{f:.2f}"]["time_s"] for f in FRACS],
        },
        "layout": layout,
        "flatten": r15["flattening"],
        #: The honest torque-vectoring measurement: the highest cornering demand
        #: each layout survives, per power level, with an open differential and
        #: with the controller. "Did it leave the road at one fixed demand" is
        #: only an illustration -- you could always ask for less.
        "limits": {pw: {k: {"off": r15["layout"][pw][f"open|{k}"]["limit_grip_use"],
                            "on": r15["layout"][pw][f"tv4|{k}"]["limit_grip_use"]}
                        for k in LAYOUT_INPUTS}
                   for pw in ("1x", "2x")},
    }

    OUT.write_text(
        "/* Measured results, exported from the experiments' own artefacts.\n"
        "   Generated by tools/export_web_data.py -- do not hand-edit. */\n"
        "window.CPData = " + json.dumps(out, separators=(",", ":")) + ";\n")
    print(f"wrote {OUT.relative_to(ROOT)}  {OUT.stat().st_size/1024:.0f} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
