"""Per-wheel forces through one corner, open differential vs torque vectoring.

**Why this exists.** Episode 15's headline is a cornering *ceiling*, which is
the honest measurement but an abstract picture. What a reader actually wants to
see is what the controller DOES: which wheel it leans on, when, and how that
differs from a differential following one fixed rule. Episode 13 drew that
(`02-which-wheels-pay.svg`) but persisted only body-level traces, so this
re-drives one lap per configuration at a matched demand and keeps the per-wheel
log `drive_lap` already produces.

Both configurations are driven at the SAME grip_use so the comparison is like
for like -- the point is where the force goes, not who survives.

    python -m tools.export_tv_wheels
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from experiments.ep13.run import Car, lap, measure
from physics import schema
from physics.track import long_exit

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "tvdata.js"
#: Well inside both cars' limits, so neither is failing and the only difference
#: on show is how each one distributes force.
GRIP_USE = 0.80
CORNERS = ("fl", "fr", "rl", "rr")


def main() -> int:
    params = schema.RV_1
    ref = measure(params)
    track = long_exit()
    out = {"gripUse": GRIP_USE, "configs": {}}

    for name in ("open", "tv4"):
        car = Car(name, params, ref)
        lp = lap(car, track, ref, GRIP_USE)
        log = lp.log
        n = len(log["s"])
        step = max(1, n // 90)          # ~90 samples is plenty to scrub
        sl = slice(None, None, step)
        d = {"s": [round(float(v), 1) for v in np.asarray(log["s"])[sl]],
             "ay": [round(float(v) / schema.G, 3) for v in np.asarray(log["a_y"])[sl]]}
        for c in CORNERS:
            d[c] = {
                "fx": [round(float(v), 0) for v in np.asarray(log[f"fx_{c}"])[sl]],
                "fy": [round(float(v), 0) for v in np.asarray(log[f"fy_{c}"])[sl]],
                "fz": [round(float(v), 0) for v in np.asarray(log[f"fz_{c}"])[sl]],
                "util": [round(float(v), 3) for v in np.asarray(log[f"util_{c}"])[sl]],
            }
        out["configs"][name] = d
        print(f"  {name:<5} {n} steps -> {len(d['s'])} samples, "
              f"valid={lp.valid}, worst slip {lp.worst_slip_deg:.1f} deg")

    OUT.write_text("/* Per-wheel forces, open diff vs torque vectoring, one lap each\n"
                   "   at matched demand. Generated by tools/export_tv_wheels.py. */\n"
                   "window.CPTv = " + json.dumps(out, separators=(",", ":")) + ";\n")
    print(f"wrote {OUT.relative_to(ROOT)}  {OUT.stat().st_size/1024:.0f} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
