"""Racing lines under disturbance, per design — for the article page.

Episode 11 drove one fixed policy over five designs and several disturbances,
keeping a sample of full trajectories. Overlaying those lines is the clearest
statement of what "fragile" means: at nominal every drivable car traces one
line, and once the grip starts varying, one of them stops.

**An honest limit, carried into the caption.** The kept trajectories are a
SAMPLE (8-14 laps) of the 120 per cell that the failure rates were measured
over. The lines show the shape of the scatter; the rates quoted alongside come
from `results_deep.json`, not from counting these.

    python -m tools.export_lines
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "linedata.js"
DESIGNS = ("040", "047", "054", "061", "065")
#: The four the page actually contrasts. 'steer' is kept because its whole
#: point is that it changes nothing.
CONDS = {"nominal": "no disturbance", "steer": "imperfect hands",
         "grip": "varying grip", "both": "both together"}
#: Every lap is resampled onto one shared distance grid, so the file stores a
#: single `s` array and just an `n` per lap. A lap that ended early simply stops
#: -- its length IS where it left the road, which the widget draws.
GRID = [i * 392.5 / 78 for i in range(79)]   # stop just inside the 392.83 m track


def main() -> int:
    z = np.load(ROOT / "experiments/ep11/out/traces.npz")
    deep = json.loads((ROOT / "experiments/ep11/out/results_deep.json").read_text())
    out = {"conds": CONDS, "designs": list(DESIGNS), "cells": {}, "rates": {}}

    out["grid"] = [round(v, 1) for v in GRID]
    for cond in CONDS:
        for d in DESIGNS:
            laps = []
            # Lap indices are NOT contiguous: the run kept the clean laps plus
            # whichever ones failed, so the failures sit at high indices. Walk
            # the actual keys rather than assuming a range, or every failure --
            # the whole point of the figure -- silently disappears.
            idx = sorted({int(k.split("_")[2]) for k in z.files
                          if k.startswith(f"{cond}_{d}_") and k.endswith("_n")})
            for i in idx:
                s, n = np.asarray(z[f"{cond}_{d}_{i}_s"]), np.asarray(z[f"{cond}_{d}_{i}_n"])
                ok = bool(z[f"{cond}_{d}_{i}_finished"])
                end = float(s[-1])
                g = [v for v in GRID if v <= end]
                laps.append({
                    "n": [round(float(v), 2) for v in np.interp(g, s, n)],
                    "ok": ok,
                })
            if laps:
                out["cells"][f"{cond}|{d}"] = laps

    # measured failure rates, from the n=120 run rather than these samples
    for key, cell in deep.get("cells", {}).items():
        if "|" in key:
            c, frac = key.split("|")
            d = f"{int(round(float(frac) * 100)):03d}"
            out["rates"][f"{c}|{d}"] = {
                "rate": cell.get("failure_rate_inside_fit"),
                "n": cell.get("n_inside_fit"),
                "fails": cell.get("failures_inside_fit"),
            }

    OUT.write_text("/* Racing lines under disturbance, sampled from Episode 11's\n"
                   "   trajectories. Generated by tools/export_lines.py. */\n"
                   "window.CPLines = " + json.dumps(out, separators=(",", ":")) + ";\n")
    cells = len(out["cells"])
    laps = sum(len(v) for v in out["cells"].values())
    print(f"wrote {OUT.relative_to(ROOT)}  {OUT.stat().st_size/1024:.0f} KB "
          f"({cells} cells, {laps} laps)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
